### ISSUE TITLE
[RFE] General test suite for dockerfiles and images needs to be configurable

### ISSUE THREAD

**Issue by phracek** [fedora-modularity/meta-test-family#147]
We need to figure out a way, how to make the test run configurable.
AC:
- [ ] users are able to configure a specific test case whether its bad result can be ignored
- [ ] users are able to configure test cases (e.g. whitelists for `rpm -`qd` checks) - the UI should be discussed with Alex
- [ ] document the new functionality

**Comment by jscotka** [comment]
# Solved by
https://github.com/fedora-modularity/meta-test-family/pull/150

Internal discussion, then we update state here

**Comment by TomasTomecek** [comment]
@jscotka can you please elaborate how is this issue solved by the linked PR? I feel like the linked PR is just about filtering and which tests should be run; the point 1 in this issue is about running all tests and just "waiving" their results

**Comment by phracek** [comment]
This is already solved by #150.
