### ISSUE TITLE
[RFE] mtf to be more user friendly

### ISSUE THREAD

**Issue by psklenar** [fedora-modularity/meta-test-family#157]
mtf script could be more user friendly python script

1. there are many environment [variables](http://meta-test-family.readthedocs.io/en/latest/user_guide/environment_variables.html), I think that they can be absolute by some "--options/--setup/--selinux etc" for reasons:

   - its more user friendly
       - and I can add some easy check if --setup was run or not(~if systems is ready to run test)
   - external docs are not needed, user will see all by --help
   - X it cannot be backward compatible, it means it has to be different name of the tool like:
`mtf2`, maybe it could be, it depends on suggestions here
-----
2. now there are more options than I can find in docs for **MTF**, like `--show-job-log` its more avocado argument.
Where can I find which we are using, I expect not all avocado options, so what to do with these type of options?
For ex there can be option smth like  `mtf2 --more_avocado_options '--show-job-log'` or something like this

3, it can uses some ~.config to save variables for avocado, or status of environment installation not slowing down process much

**Comment by psklenar** [comment]
#162

**Comment by phracek** [comment]
This is already fixed by #162. Closing it.
