### ISSUE TITLE
is mtf.1 up to date?

### ISSUE THREAD

**Issue by TomasTomecek** [fedora-modularity/meta-test-family#171]
After the rebase of mtf command, is the manpage still up to date?

**Comment by phracek** [comment]
@psklenar Can you please update man page for `mtf`? https://github.com/fedora-modularity/meta-test-family/blob/devel/man/mtf.1

**Comment by psklenar** [comment]
@phracek , yes, taking , I will look at this.

**Comment by psklenar** [comment]
I used build_manpages : https://github.com/praiskup/build_manpages/tree/5c16e8f12e3b93f525e7220f1353c06bf825e0a2


#175

**Comment by phracek** [comment]
Issue is fixed.
