### ISSUE TITLE
Replace microdnf test with $pkg clean all test

### ISSUE THREAD

**Issue by phracek** [fedora-modularity/meta-test-family#19]
MTF tests whether microdnf is used. MTF will be used in RHEL and CentOS and therefore
instead of testing microdnf it would be good to test whether clean all is used so that dnf/yum garbage is removed.

**Comment by TomasTomecek** [comment]
I would personally test this by inspecting final image and checking whether metadata for specific package manager in `/var/cache` are truly missing.

**Comment by phracek** [comment]
The test is removed. Issue can be closed.
