### ISSUE TITLE
Unable to install mtf from copr on rhel-7

### ISSUE THREAD

**Issue by lukaszachy** [fedora-modularity/meta-test-family#208]
I added  copr repo: https://copr.fedorainfracloud.org/coprs/phracek/meta-test-family/repo/epel-7/phracek-meta-test-family-epel-7.repo
but yum install meta-test-family failed with

Error: Package: meta-test-family-0.7.8-1.el7.centos.noarch (phracek-meta-test-family)
           Requires: python2-dockerfile-parse

Please bundle that package to your copr repo or provide a rhel-7 way to install mtf

FYI: pip install works

**Comment by TomasTomecek** [comment]
would it be okay to install dependencies from epel?

**Comment by lukaszachy** [comment]
EPEL should be OK, imho.

**Comment by phracek** [comment]
python-dockerfile-parse exists in epel. New build is ongoing soon.

**Comment by phracek** [comment]
The issue should be fixed by build https://koji.fedoraproject.org/koji/buildinfo?buildID=1044126.
Issue which fixes this bug is #210

**Comment by phracek** [comment]
This is already fixed and works properly.
