### ISSUE TITLE
Notes on packaging

### ISSUE THREAD

**Issue by bkabrda** [fedora-modularity/meta-test-family#22]
Here are some notes/questions that I think might be useful to discuss/think through:

* What is the reason to put modulelint it data files (/usr/share)? AFAICS it's just another Python module, so it should go alongside `moduleframework` or live inside it, IMO.
* I'd recommend creating a `requirements.txt` file, which is a de-facto standard in Python community to track dependencies.
* I don't understand following line in the spec: `chmod a+x %{buildroot}%{python_sitelib}/%{framework_name}/{module_framework,mtf_generator,bashhelper,setup}.py` - The `python_sitelib` shouldn't contain executable files. Either these files shouldn't be executable at all or they should have their functionality available through an endpoint.

**Comment by phracek** [comment]
@bkabrda Please review PR #63 . Thanks.

**Comment by phracek** [comment]
Closing.
