### ISSUE TITLE
check architecture label

### ISSUE THREAD

**Issue by fkluknav** [fedora-modularity/meta-test-family#232]
Hi,

docker marks the architecture in image metada like "Architecture": "amd64".
Osbs puts labels like "architecture": "x86_64" into the image automagically.
I suggest to disable/reverse/rethink DockerLabelsTests.test_architecture_label_exists. The label should be in the image. That does not mean it should be in the Dockerfile, it is not the same thing here. Fedora container guidelines say "Optional: if omitted, it will be built for all supported Fedora Architectures".

**Comment by TomasTomecek** [comment]
I agree with removing such test.
