### ISSUE TITLE
Do not report missing io.k8s.description if description is present.

### ISSUE THREAD

**Issue by fkluknav** [fedora-modularity/meta-test-family#235]
Do not report missing 'io.k8s.description' if 'description' is present. If one exists, the build system copies it to the other. The same applies for the other way, missing description and present io.k8s.description. No need to have both in Dockerfiles.

**Comment by TomasTomecek** [comment]
We have already moved the checks from this project into a dedicated project: https://github.com/user-cont/colin

Could you please report there? Thank you.

**Comment by fkluknav** [comment]
https://github.com/user-cont/colin/issues/129
