### ISSUE TITLE
run and usage together

### ISSUE THREAD

**Issue by fkluknav** [fedora-modularity/meta-test-family#236]
Hi,

Fedora container guidelines say: "run or usage | Either provides an Atomic run line, or a human readable example of container execution"

Tests enforce both at the same time.

**Comment by TomasTomecek** [comment]
We have already moved the checks from this project into a dedicated project: https://github.com/user-cont/colin

Could you please report there? Thank you.

**Comment by fkluknav** [comment]
https://github.com/user-cont/colin/issues/128
