### ISSUE TITLE
Update SPEC file according new MTF name

### ISSUE THREAD

**Issue by phracek** [fedora-modularity/meta-test-family#30]
#28 updates documentation including SPEC file.
Old name SPEC name was modularity-testing-framework.spec with name modularity-testing-framework

How to update SPEC file according to new name.
There are two options how to handle it:

1. keep the same name and add to spec file http://pkgs.fedoraproject.org/cgit/rpms/coreutils.git/tree/coreutils.spec?h=f26#n130
    In our case: Provides: meta-test-family = %{version} - %{release}
1. Mark modularity-testing-framework as obsolete and introduce the new name. I don't know in my mind, If the new package request will be needed. Including new Fedora dist-git repo.

Conversation from #28 
@phracek , I updated copr repo name in docs... As per spec, I would go with the option number two. And I also would change all occurrences of moduleframework to mtf, agree? If so, I will proceed.
@alexxa Let's discuss it together with other folks. I will create a new issue, so we can merge documentation.

What do you thing folks? @ignatenkobrain @TomasTomecek

**Comment by ignatenkobrain** [comment]
I would prefer to rename it. https://fedoraproject.org/wiki/Package_Renaming_Process

**Comment by phracek** [comment]
ok, I will start with package renaming process. https://bugzilla.redhat.com/show_bug.cgi?id=1477154
