### ISSUE TITLE
[RFE] MTF should provide scripts for preparing/cleaning/running tests

### ISSUE THREAD

**Issue by phracek** [fedora-modularity/meta-test-family#31]
@jscotka would like to change MTF behaviour a propose following.

MTF should provide set of scripts which will care about following:

- [x] `mtf-env-set` which will prepare environment for specific tests. Like `MODULE=docker mtf-setup` which will prepare an environment for testing in docker
- [x] `mtf` will only run tests and does not care about setting environment, cleaning environment.
- [x] `mtf-env-clean` which will clean environment after testing. Like `MODULE=docker mtf-cleanup`

@TomasTomecek @jscotka @alexxa @bkabrda What do you think about it?
Do you like the script names?

**Comment by TomasTomecek** [comment]
seems very related to https://fedoraproject.org/wiki/Changes/InvokingTests

**Comment by jscotka** [comment]
solved by: 
    https://github.com/fedora-modularity/meta-test-family/pull/44

**Comment by phracek** [comment]
This is solved by #44 . Closing for now.
