### ISSUE TITLE
Create package for PyPi community

### ISSUE THREAD

**Issue by phracek** [fedora-modularity/meta-test-family#35]
It would be nice to have the package on PyPi.

**Comment by bkabrda** [comment]
I'll work on this.

**Comment by bkabrda** [comment]
So I verified that MTF seems to be installable from an sdist package both to a virtualenv and systemwide without any changes necessary. This means that we should be able to just upload the current code to PyPI in sdist and be done with it. I'm assuming you folks might have an organization/user on PyPI that you want to use for this, so I'll leave this up to you. Feel free to give me a shout if you need any help with this.

**Comment by phracek** [comment]
https://pypi.python.org/pypi/meta-test-family/0.6.1
