### ISSUE TITLE
invalid link in documentation

### ISSUE THREAD

**Issue by KarstenHopp** [fedora-modularity/meta-test-family#36]
The link to the list of Environment variables on http://meta-test-family.readthedocs.io/en/latest/user_guide/index.html point to a non-existant page http://meta-test-family.readthedocs.io/en/latest/user_guide/environment_variables  
It should be http://meta-test-family.readthedocs.io/en/latest/user_guide/environment_variables.html

**Comment by KarstenHopp** [comment]
well, all the links on that page are invalid ;-(

**Comment by alexxa** [comment]
@KarstenHopp, Thank you for reporting it. Fixed by commit ddd5c0a and should be available soon when devel is merged into master. May I close this issue?

**Comment by KarstenHopp** [comment]
the commit looks good to me
