### ISSUE TITLE
Make sure that links in documentation are valid

### ISSUE THREAD

**Issue by TomasTomecek** [fedora-modularity/meta-test-family#38]
I've got a pointer by colleague that some links in documentation are broken, e.g.:

Section [User Guide](http://meta-test-family.readthedocs.io/en/latest/user_guide/index.html), first three links are broken:
http://meta-test-family.readthedocs.io/en/latest/user_guide/how_to_write_conf_file
http://meta-test-family.readthedocs.io/en/latest/user_guide/how_to_write_conf_file#multiline-bash-snippet-tests
http://meta-test-family.readthedocs.io/en/latest/user_guide/environment_variables

**Comment by alexxa** [comment]
@TomasTomecek and @phracek it was reported and fixed yesterday. See issue #36.

**Comment by TomasTomecek** [comment]
Still getting 404's. Can you trigger a docs rebuild and publish?

**Comment by alexxa** [comment]
@TomasTomecek The Fix will be online when devel is merged into master. According to @jscotka ETA is today or in the worst case tomorrow.

**Comment by TomasTomecek** [comment]
okay, thanks for update

**Comment by TomasTomecek** [comment]
I just got pinged by @alexxa that this is now fixed online.
