### ISSUE TITLE
logs from MTF could show  list of all commands which were used

### ISSUE THREAD

**Issue by psklenar** [fedora-modularity/meta-test-family#58]
log /root/avocado/job-results/latest/job.log , mtf

/root/avocado/job-results/latest/job.log has to show some nice list of run commands which is procedure of tests.

Something like:
sudo grep "Command '" /root/avocado/job-results/latest/job.log
+
there could be some difference when commands are run at your computer or in container/nspawn etc. Now its very very hard to read it.

**Comment by phracek** [comment]
Issue does not make sense. `mtf` provides better human readable output.
