### ISSUE TITLE
allow using aexpect for module framework

### ISSUE THREAD

**Issue by jscotka** [fedora-modularity/meta-test-family#6]
COPY: https://pagure.io/modularity-testing-framework/issue/4

As I've fixed issue #1 there is problem that it is just for not complex cases, for complex case, we have to use aexpect, it is possible to use aexpect directly on host, but it has to be able to ruin commans inside modules
https://github.com/avocado-framework/aexpect
example: 
```
from aexpect import ShellSession
a=ShellSession("/bin/sh")
a.cmd("true")
```

**Comment by phracek** [comment]
We can use this I don't see what is the problem about. Closing it. See https://github.com/container-images/dovecot/blob/master/tests/dovecot.py#L36
