### ISSUE TITLE
logs are too verbose by seeing output from equiv of `rpm -ql $(rpm -qa)`

### ISSUE THREAD

**Issue by TomasTomecek** [fedora-modularity/meta-test-family#64]
We've just run into [an issue](https://github.com/container-images/container-image-template/pull/38) that MTF outputs megabytes of logs when run with `avocado run --show-job-log`. The issue seems to be that MTF logs to stdout something like this: `rpm -ql $(rpm -qa)`, snippet:

```
"rpm -qa"' finished with 0 after 0.224642038345s
Running 'docker exec 53c6521953c0b44c71734fcdcedf59524c2e7ffa58ca8e5e4392c0917905c11b bash -c "rpm -ql fedora-repos-26-1.noarch"'
...
```

Can we get those command outputs not logged?

**Comment by jscotka** [comment]
We can close this bug, because there is some fix on template part, and also you can use:
self.run("command", verbose=False) and there will be no output of commands to log `verbose=False` forwarded to `process.run` method and causes that output of command is not displayed in log.
