### ISSUE TITLE
Container helper should not try to install packages

### ISSUE THREAD

**Issue by bkabrda** [fedora-modularity/meta-test-family#66]
So I'm using MTF for container testing and it's taking an insane amount of time (e.g. 100 seconds) before the `self.start()` method finishes. I noticed that if `self.getPackageList()` is not empty, it will try to run some `dnf install` commands. I honestly have no idea why it's doing that. The container should already contain all the packages (that's what is being tested) and nothing should get installed on host.

So when I remove the whole condition at [1], my test takes 12 seconds instead of 112 and still passes ok. I think it should be safe to remove this and I'll be happy to send a PR, but I first wanted to clarify why this condition is there in the first place.

[1] https://github.com/fedora-modularity/meta-test-family/commit/638146dc98d1b09b1c691eab357886b88864e328#diff-3319a1c7872defb83c1bac839ad9efddR173

**Comment by jscotka** [comment]
it is in devel branch
