### ISSUE TITLE
baseruntime check

### ISSUE THREAD

**Issue by bkabrda** [fedora-modularity/meta-test-family#73]
Why are all images required to be based on `baseruntime/baseruntime`? What if I don't want to use baseruntime at all or my image is based on image that is based on baseruntime (i.e. I do use baseruntime transitively)?

**Comment by bkabrda** [comment]
(Note: this is about `tools/modulelint/modulelint.py:DockerfileLinter.testDockerFromBaseruntime`)

**Comment by phracek** [comment]
This has to be rewritten so, MTF will check if image mentioned in FROM really exists. That would be enough

**Comment by rpitonak** [comment]
same for the `tools/modulelint/modulelint.py:DockerfileLinter.testDockerRunMicrodnf`.

**Comment by bkabrda** [comment]
@phracek so I'm not sure about this. Testing whether the base image exists or not is a one-time thing. The image can disappear one second after the test is done or it can be in a registry that's temporarily unaccessible. Personally, I don't think this a very good candidate for check in a linter-type tool, but I guess I can live with it if it checks the actual base image from the Dockerfile.
