### ISSUE TITLE
Show logs or an output in case some tests fail

### ISSUE THREAD

**Issue by phracek** [fedora-modularity/meta-test-family#85]
MTF should be able to show failed logs. Logs which should be visible as soon as mtf finishes should be FAILED, so user should not open log and find out FAILED tests.
Think about if there should be some options for allowing this issue.

The PR #63 brings a bash script called `mtf` which should be enhanced based on this issue.

**Comment by psklenar** [comment]
@phracek
here you can see modified output from mtf command (see the end of video ... like 2:15) :
http://people.redhat.com/psklenar/pub/out.ogv

what do you think?

**Comment by phracek** [comment]
Issue is fixed by PR #105
