### ISSUE TITLE
[RFE] MTF API library: function for checking specific container issues

### ISSUE THREAD

**Issue by phracek** [fedora-modularity/meta-test-family#86]
MTF has to provide a API library with function which will check these container issues:

- [ ] support whether daemon serves content on specific port
- [ ] checking whether response returns 200
- [ ] add support for specific combination of container parameters which should not work
- [ ] function for check if specific file exists inside container
- [ ] function for check rpm signarures
- [ ] function for check help page and things which are important.
- [ ] create a document under api http://meta-test-family.readthedocs.io/en/latest/api/index.html which will provide list and description. I would prefer to name it like API.

Think about to create new modules in folder like moduleframework/api/

**Comment by phracek** [comment]
For this issue Github repo https://github.com/fedora-modularity/conu/ was created.

**Comment by dhodovsk** [comment]
This issue was moved to fedora-modularity/conu#4
