### ISSUE TITLE
Enhance / improve dockerlint.py class according to Container Best Practises

### ISSUE THREAD

**Issue by phracek** [fedora-modularity/meta-test-family#87]
The classes mentioned in https://github.com/fedora-modularity/meta-test-family/blob/devel/tools/modulelint.py
has to be enhanced / rewritten so that it will cover Container Best Practices.

Nowadays, it contains several checks in DockerfileSanitize class:
- test_architecture_in_env_and_label_exists
- test_name_in_env_and_label_exists
- test_release_label_exists
- test_version_label_exists
- test_com_red_hat_component_label_exists
- test_iok8s_description_exists - WILL BE REMOVED
- test_io_openshift_expose_services_exists - WILL BE REMOVED
- test_io_openshift_tags_exists - WILL BE REMOVED

The other checks in DockerfileLinterInContainer class 
- [x] test_docker_nodocs https://github.com/fedora-modularity/meta-test-family/pull/97
- [x] test_docker_clean_all https://github.com/fedora-modularity/meta-test-family/pull/97

Implementation of other checks based on http://docs.projectatomic.io/container-best-practices/
- [x] FROM is first directive in Dockerfile
- [x] FROM contains valid format like is mentioned here http://docs.projectatomic.io/container-best-practices/#_line_rule_section
- [x] check help.md is mentioned in Dockerfile
- [x] check if help.md is in correct location
- [x] check if EXPOSE ports contain only numbers
- [x] check if ADD contains real files in directory
- [x] check if COPY copies present files in directory
- [x] check if USER directive contains only numbers - this  is not valid since USER can be specified by digits or by string.

Checks if help.md file contains following: http://docs.projectatomic.io/container-best-practices/#_sample_template
- [x] IMAGE_NAME tag
- [x] MAINTAINER
- [x] NAME
- [x] DESCRIPTION
- [x] USAGE
- [x] ENVIRONMENT VARIABLES
- [x] SECURITY IMPLICATIONS

Optional things to check
- [ ] OpenShift labels io.k8s.{description,display-name}
- [ ] OpenShift labels io.openshift.{expose,tags}
- [ ] Atomic labels like RUN, INSTALL, UNINSTALL

**Comment by phracek** [comment]
@TomasTomecek @bkabrda @jscotka @eliskasl Can you please have a look on this issues and make comments?

**Comment by TomasTomecek** [comment]
I'll be honest: I don't like concept of a dockerfile linter, I think it's
better to build the image and verify its content. Dockerfile is a non-standard
format and thus parsing and verifying it is just too complicated. It's easier
to check the image -- the image can be produced with whatever method. Therefore
I think we should "see the future" here and focus on verifying images rather
than Dockerfiles, which I hope we'll stop using at some point.


> Checks if help.md file contains following: http://docs.projectatomic.io/container-best-practices/#_sample_template

This is overkill. I would just check whether it's present and is named right.


> OpenShift labels io.k8s.{description,display-name}
> OpenShift labels io.openshift.{expose,tags}
> Atomic labels like RUN, INSTALL, UNINSTALL

These could produce warnings or something like that.


Here are some more ideas:
 * No documentation packaged in RPMs is being installed (we may need whitelists).
 * Service is not running as root by default (whitelists?).
 * Container is being invoked in exec form (docker run $IMAGE has the service as PID 1, not bash).
 * The container can be invoked:
   * run interactive bash inside (which will accept commands)
   * image can be run with -t -i options
   * image can be run without -t -i options
   * do the same for `docker exec`
 * There are no package manager metadata left in any of the image’s layers.
 * There are no two RUN instructions used in a row.
   * The main point here is: are there any files lingering in some layer?

**Comment by phracek** [comment]
In case EXPOSE, if it is not number but alphanum, build fails.
In case ADD, if file/direcotries does not exist, build fails.
In case COPY, if file/direcotries does not exists, build fails.

This does not make sense to test it.

**Comment by phracek** [comment]
There is another Pull Request which cares about package manager metadata and nodocs here #97. 

@TomasTomecek Can you please explain me how to use two RUN instructions in a row? I was not able to build container in case like `RUN foo1 && RUN foo2`.

**Comment by phracek** [comment]
This PR solved help.md file checks #125 .

**Comment by TomasTomecek** [comment]
```
FROM registry.fedoraproject.org/fedora:26
RUN dnf install -y htop
RUN dnf install -y strace
RUN dnf clean all
```

Worst thing image maintainers can do.

**Comment by phracek** [comment]
Except OpenShift and atomic labels, all is done. Closing for now.
