### ISSUE TITLE
[RFE] MTF API requirements: provide a function for running SQL commands for a specific handle

### ISSUE THREAD

**Issue by phracek** [fedora-modularity/meta-test-family#88]
MTF should be able to specify function for running SQL commands for a specific handle, which in real runs a separate container (ideally re-using the same instance for more commands), and checks output.. but the point is to have ability to specify such function in the component library

**Comment by phracek** [comment]
For this issue Github repo https://github.com/fedora-modularity/conu/ was created.

**Comment by dhodovsk** [comment]
This issue was moved to fedora-modularity/conu#3
