### ISSUE TITLE
[RFE] provide a functionality for testing S2I images

### ISSUE THREAD

**Issue by phracek** [fedora-modularity/meta-test-family#90]
When testing the s2i (source-to-image) support 
- [ ] I just pass an image name, applications repo or path (both needs to be supported) and run command (sometimes additional options are needed)
- [ ] the framework will run the `s2i build`
- [ ] will check that the s2i usage works, etc …

**Comment by phracek** [comment]
@hhorak @praiskup Please provide more info what kind of other checks could be useful for you.

**Comment by praiskup** [comment]
-1, specifying the needs here doesn't make sense.  For me it is much, much cheaper to actually go and write the library myself.  That's the point, please -- write the "real-life" tests and write a lib which helps you with this (not the other way around).

I would suggest you to have a look at any s2i/non-s2i image testing script, and rewrite some of them (e.g. postgrsql).  If you are able to write that testsuite with smaller line-count, you have a good library for testing images.

**Comment by praiskup** [comment]
More concretely, we have the `$TEST_LIST` in [1].  Having a look at that, it should be 100% clear what abstraction/checks/asserts are needed.  Let me know if you want some more examples.

 https://github.com/sclorg/postgresql-container/blob/0b630e19ef99cc3af50cc9f22866d05cdf497e3e/hack/run_test

**Comment by praiskup** [comment]
Also, you don't have to replace complete testsuite -> we can calmly have two testsuites in each image repository in parallel (hooked into `make test` target).  So, let's start with the most trivial test-cases.  Plus, any new useful testcase is very appreciated! 👍

**Comment by phracek** [comment]
For this issue Github repo https://github.com/fedora-modularity/conu/ was created.

**Comment by dhodovsk** [comment]
This issue was moved to fedora-modularity/conu#2
