### ISSUE TITLE
Print message what mtf-env-set does during its work

### ISSUE THREAD

**Issue by phracek** [fedora-modularity/meta-test-family#91]
Nowadays mtf-env-set does something but does not print any information what was done.
Command line interface should inform user what was changed or what's going on.

**Comment by psklenar** [comment]
I partially added some info messages by :
https://github.com/fedora-modularity/meta-test-family/pull/99

**Comment by psklenar** [comment]
better code:
#102

**Comment by psklenar** [comment]
@phracek : could we close this issue?

**Comment by psklenar** [comment]
already in devel branch
