### ISSUE TITLE
[RFE] Provide a simple UX for working with volumes

### ISSUE THREAD

**Issue by hhorak** [fedora-modularity/meta-test-family#92]
When working with volumes during container image testing, the directory typically needs to be created with correct owner, attributes and selinux. Then this directory may be used by one or more containers during the test and test may want to verify that some content is present in the directory. For all that the testing library should provide a simple user experience.

**Comment by phracek** [comment]
@hhorak This is relevant for https://github.com/fedora-modularity/conu/ or to this repo? What do you think?
My suggestion is to MTF.

**Comment by TomasTomecek** [comment]
I kind-of missed setting ownership, here's the PR: https://github.com/fedora-modularity/conu/pull/64

once merged, all of the suggestions from Honza are implemented
